version: '3.1'
services:
  app:
    container_name: web_server
    build: 
      context: ./server
    depends_on:
      - db
    ports:
      - "3001:8005"
    restart: on-failure:5

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: estructuras
      MYSQL_DATABASE: proyecto
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - ./data:/var/lib/mysql
    restart: always
